apiVersion: apps/v1
kind: Deployment
metadata:
  name: techblog-notification-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: techblog-notification-api
    spec:
      containers:
      - name: notificationapi
        image: enzotlucas31/notificationapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
        app: techblog-notification-api
---
apiVersion: v1
kind: Service
metadata:
  name: techblog-notification-api
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: techblog-notification-api

      