apiVersion: apps/v1
kind: Deployment
metadata:
  name: techblog-sendemail-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: techblog-sendemail-worker
    spec:
      containers:
      - name: sendemailworker
        image: enzotlucas31/sendemailworker:latest
        ports:
        - containerPort: 80
  selector:
    matchLabels:
        app: techblog-sendemail-worker