apiVersion: apps/v1
kind: Deployment
metadata:
  name: techblog-newsapi-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: techblog-newsapi-api
    spec:
      containers:
      - name: newsapi
        image: enzotlucas31/newsapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
        app: techblog-newsapi-api
---
apiVersion: v1
kind: Service
metadata:
  name: techblog-newsapi-api
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: techblog-newsapi-api